import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { ALLOWLIST, SftpBridgeAgent, TARGET_KEYS, safeRemotePath, sha256, validateReleaseId } from '../bridge/sftp-agent.mjs';

const token = 'x'.repeat(48);
const baseline = Object.fromEntries(ALLOWLIST.map((key) => [`/instance/OblivionControl/${key}`, Buffer.from(`old:${key}`)]));
const content = Object.fromEntries(ALLOWLIST.map((key) => [key, Buffer.from(`new:${key}`)]));
const manifest = { files: ALLOWLIST.map((fileKey) => ({ targetKey: Object.entries(TARGET_KEYS).find(([, relative]) => relative === fileKey)?.[0], releasePath: fileKey, size: content[fileKey].length, sha256: sha256(content[fileKey]) })) };

class MockSftp {
  constructor(seed = baseline) { this.files = new Map(Object.entries(seed).map(([k, v]) => [k, Buffer.from(v)])); this.ops = []; this.failRenameAt = null; this.renameCount = 0; this.failConnect = false; this.hostKey = 'SHA256:test'; }
  async connect(config) { this.ops.push(['connect', config]); if (this.failConnect) throw new Error('INJECTED_CONNECT_FAILURE'); if (!config.hostVerifier(this.hostKey)) throw new Error('HOST_KEY_REJECTED'); }
  async end() { this.ops.push(['end']); }
  async exists(p) { return p === '/instance' || this.files.has(p) || [...this.files.keys()].some((k) => k.startsWith(`${p}/`)); }
  async mkdir(p) { this.ops.push(['mkdir', p]); }
  async list(p) { this.ops.push(['list', p]); return [...this.files.keys()].filter((k) => k.startsWith(`${p}/`)).map((name) => ({ name })); }
  async get(p) { if (!this.files.has(p)) throw new Error(`ENOENT:${p}`); return Buffer.from(this.files.get(p)); }
  async put(data, p) { this.ops.push(['put', p]); this.files.set(p, Buffer.from(data)); }
  async rename(from, to) { this.renameCount += 1; this.ops.push(['rename', from, to]); if (this.failRenameAt === this.renameCount) throw new Error('INJECTED_RENAME_FAILURE'); this.files.set(to, this.files.get(from)); this.files.delete(from); }
  async delete(p) { this.ops.push(['delete', p]); this.files.delete(p); }
}

function mockFetch({ badHash = false, heartbeatFailure = false } = {}) {
  return async (url, options = {}) => {
    const u = new URL(url);
    if (u.pathname.endsWith('/releases/latest')) return { ok: true, json: async () => ({ releaseId: 'rel-1' }) };
    if (u.pathname.endsWith('/manifest')) return { ok: true, json: async () => badHash ? { files: manifest.files.map((x, i) => i === 0 ? { ...x, sha256: 'BAD' } : x) } : manifest };
    if (u.pathname.includes('/files/')) { const key = decodeURIComponent(u.pathname.split('/files/')[1]); const relative = Object.hasOwn(TARGET_KEYS, key) ? TARGET_KEYS[key] : key; return { ok: true, arrayBuffer: async () => content[relative] }; }
    if (u.pathname.endsWith('/heartbeat')) { if (heartbeatFailure) return { ok: false, status: 503, json: async () => ({}) }; return { ok: true, json: async () => ({ ok: true, body: JSON.parse(options.body) }) }; }
    throw new Error(`UNEXPECTED_FETCH:${u.pathname}`);
  };
}

function agent(transport, extra = {}) { return new SftpBridgeAgent({ apiBase: 'https://example.test', token, transport, hostFingerprint: 'SHA256:test', fetchImpl: mockFetch(), stateStore: {}, ...extra }); }

test('SFTP connect and remote root discovery', async () => { const t = new MockSftp(); const result = await agent(t).connect(); assert.equal(result.instanceExists, true); assert.equal(result.root, '/instance/OblivionControl'); });
test('allowlist and traversal are fail-closed', async () => { assert.throws(() => new SftpBridgeAgent({ apiBase: 'x', token, transport: new MockSftp(), remoteRoot: '/instance/../evil', fetchImpl: mockFetch() }), /REMOTE_ROOT_INVALID|REMOTE_ROOT_OUTSIDE_INSTANCE/); assert.throws(() => safeRemotePath('/instance/OblivionControl', '../evil.json'), /REMOTE_PATH_NOT_ALLOWLISTED/); assert.throws(() => safeRemotePath('/instance/OblivionControl', 'players.db'), /REMOTE_PATH_NOT_ALLOWLISTED/); });
test('apply creates backup, uploads tmp, validates SHA and renames atomically', async () => { const t = new MockSftp(); const result = await agent(t).applyLatest(); assert.equal(result.status, 'APPLIED'); assert.equal(t.files.get('/instance/OblivionControl/Catalog/items.json').toString(), 'new:Catalog/items.json'); assert.ok(t.files.has('/instance/OblivionControl/.backups/rel-1/manifest.json')); assert.ok(t.ops.some((x) => x[0] === 'rename')); });
test('remote SHA mismatch prevents writes', async () => { const t = new MockSftp(); const a = new SftpBridgeAgent({ apiBase: 'https://example.test', token, transport: t, hostFingerprint: 'SHA256:test', fetchImpl: mockFetch({ badHash: true }) }); await assert.rejects(() => a.applyLatest(), /RELEASE_FILE_SHA256_MISMATCH/); assert.equal(t.ops.filter((x) => x[0] === 'put').length, 0); });
test('partial failure rolls back already changed files byte-for-byte', async () => { const t = new MockSftp(); t.failRenameAt = 2; await assert.rejects(() => agent(t).applyLatest(), /INJECTED_RENAME_FAILURE/); for (const [p, data] of Object.entries(baseline)) assert.deepEqual(t.files.get(p), data); });
test('rollback restores byte-for-byte from remote backup', async () => { const t = new MockSftp(); const a = agent(t); await a.applyLatest(); assert.equal(t.files.get('/instance/OblivionControl/TradeSystem/prices.json').toString(), 'new:TradeSystem/prices.json'); const result = await a.rollback('rel-1'); assert.equal(result.status, 'ROLLED_BACK'); for (const [p, data] of Object.entries(baseline)) assert.deepEqual(t.files.get(p), data); });
test('dry run performs no JSON writes', async () => { const t = new MockSftp(); const a = agent(t, { dryRun: true }); const before = new Map([...t.files].map(([k, v]) => [k, v.toString()])); const result = await a.applyLatest(); assert.equal(result.mode, 'DRY_RUN'); assert.equal(t.ops.filter((x) => ['put', 'rename', 'delete'].includes(x[0])).length, 0); assert.deepEqual(new Map([...t.files].map(([k, v]) => [k, v.toString()])), before); });
test('host key match passes and mismatch/missing production fail closed', async () => { const match = new MockSftp(); await agent(match).connect(); await assert.rejects(() => new SftpBridgeAgent({ apiBase: 'x', token, transport: new MockSftp(), fetchImpl: mockFetch(), hostFingerprint: 'SHA256:wrong' }).connect(), /HOST_KEY_REJECTED/); await assert.rejects(() => new SftpBridgeAgent({ apiBase: 'x', token, transport: new MockSftp(), fetchImpl: mockFetch(), hostFingerprint: '' }).connect(), /SFTP_HOST_FINGERPRINT_REQUIRED/); });
test('operations close after success, apply error, connect error and rollback error', async () => { const success = new MockSftp(); await agent(success).applyLatest(); assert.equal(success.ops.at(-1)[0], 'end'); const applyError = new MockSftp(); applyError.failRenameAt = 1; await assert.rejects(() => agent(applyError).applyLatest()); assert.equal(applyError.ops.at(-1)[0], 'end'); const connectError = new MockSftp(); connectError.failConnect = true; await assert.rejects(() => agent(connectError).applyLatest()); assert.equal(connectError.ops.at(-1)[0], 'end'); const rollbackError = new MockSftp(); const a = agent(rollbackError); await a.applyLatest(); rollbackError.files.delete('/instance/OblivionControl/.backups/rel-1/manifest.json'); await assert.rejects(() => a.rollback('rel-1')); assert.equal(rollbackError.ops.at(-1)[0], 'end'); });
test('release ids reject traversal, absolute paths, invalid chars and oversized values', () => { for (const value of ['../x', '..\\x', '/absolute', 'a/b', 'a\\b', 'a%b', '', 'a'.repeat(97)]) assert.throws(() => validateReleaseId(value), /RELEASE_ID_INVALID/); });
test('concurrent apply is rejected and replay does not write', async () => { const t = new MockSftp(); const a = agent(t); const first = a.applyLatest(); await assert.rejects(() => a.applyLatest(), /APPLY_ALREADY_IN_PROGRESS/); await first; const puts = t.ops.filter((x) => x[0] === 'put').length; const replay = await a.applyLatest(); assert.equal(replay.status, 'ALREADY_APPLIED'); assert.equal(t.ops.filter((x) => x[0] === 'put').length, puts); });
test('failed apply releases lock and cleans temporary files', async () => { const t = new MockSftp(); t.failRenameAt = 1; const a = agent(t); await assert.rejects(() => a.applyLatest()); assert.equal(a.applyState, 'IDLE'); assert.equal([...t.files.keys()].some((p) => p.includes('.tmp-') || p.includes('.rollback-tmp-')), false); t.failRenameAt = null; assert.equal((await a.applyLatest()).status, 'APPLIED'); });
test('persistent state writes and reloads across bridge instances', async () => { const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'obc-state-')); const stateFile = path.join(directory, 'oblivion-control', 'sftp-bridge-state.json'); const t = new MockSftp(); const first = new SftpBridgeAgent({ apiBase: 'https://example.test', token, transport: t, hostFingerprint: 'SHA256:test', fetchImpl: mockFetch(), stateFile, serverId: 'test-server' }); assert.equal((await first.applyLatest()).status, 'APPLIED'); const saved = JSON.parse(fs.readFileSync(stateFile, 'utf8')); assert.equal(saved.currentReleaseId, 'rel-1'); assert.equal(saved.status, 'APPLIED'); const second = new SftpBridgeAgent({ apiBase: 'https://example.test', token, transport: t, hostFingerprint: 'SHA256:test', fetchImpl: mockFetch(), stateFile, serverId: 'test-server' }); const puts = t.ops.filter((x) => x[0] === 'put').length; assert.equal((await second.applyLatest()).status, 'ALREADY_APPLIED'); assert.equal(t.ops.filter((x) => x[0] === 'put').length, puts); });
test('corrupt persistent state fails closed and state contains no secrets', () => { const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'obc-state-corrupt-')); const stateFile = path.join(directory, 'state.json'); fs.writeFileSync(stateFile, '{not-json'); assert.throws(() => new SftpBridgeAgent({ apiBase: 'x', token, transport: new MockSftp(), fetchImpl: mockFetch(), stateFile }), /SFTP_STATE_CORRUPT/); });
test('successful apply with heartbeat failure does not reapply on retry', async () => { const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'obc-state-heartbeat-')); const stateFile = path.join(directory, 'state.json'); const t = new MockSftp(); const first = new SftpBridgeAgent({ apiBase: 'https://example.test', token, transport: t, hostFingerprint: 'SHA256:test', fetchImpl: mockFetch({ heartbeatFailure: true }), stateFile }); assert.equal((await first.applyLatest()).status, 'APPLIED_HEARTBEAT_PENDING'); const saved = JSON.parse(fs.readFileSync(stateFile, 'utf8')); assert.equal(saved.status, 'APPLIED_HEARTBEAT_PENDING'); const puts = t.ops.filter((x) => x[0] === 'put').length; const second = new SftpBridgeAgent({ apiBase: 'https://example.test', token, transport: t, hostFingerprint: 'SHA256:test', fetchImpl: mockFetch({ heartbeatFailure: true }), stateFile }); assert.equal((await second.applyLatest()).status, 'APPLIED_HEARTBEAT_PENDING'); assert.equal(t.ops.filter((x) => x[0] === 'put').length, puts); assert.equal(JSON.stringify(saved).includes(token), false); });
